openapi: 3.0.3
info:
  title: API Superhéroes
  version: 1.0.0
  description: |
    Plantilla  de Open Api 3.0.4 para consultar, crear y eliminar superheroes.
     
     ### Equipo 1
    - Brandon Arcos
    - Alberto Linan
    - Juan Hernandez
    - Roberto Alvarez
    
    [superheroes.git](https://github.com/Bnunez17/BRXJJ)
servers:
  - url: http://localhost/Superheroes
    description: Apache XAMPP (htdocs/Superheroes)

paths:
  /superheroe.php:
    post:
      summary: Crear un superhéroe
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                Nombre:
                  type: string
                  example: "Infernox"
                Peso:
                  type: number
                  example: 90
                Altura:
                  type: number
                  example: 1.85
                Poder:
                  type: number
                  example: 95
                created:
                  type: string
                  format: date-time
                  example: "2025-07-05T18:30:00Z"
      responses:
        '200':
          description: Superhéroe guardado exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Superhéroe guardado exitosamente
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 40
                      Nombre:
                        type: string
                        example: Infernox
                      Peso:
                        type: number
                        example: 90
                      Altura:
                        type: number
                        example: 1.85
                      Poder:
                        type: number
                        example: 95
                      created:
                        type: string
                        format: date-time
                        example: "2025-07-11T01:14:28+00:00"

    get:
      summary: Obtener superhéroes paginados
      parameters:
        - in: query
          name: page
          required: false
          description: Número de página (solo 1 o 2)
          schema:
            type: integer
            default: 1
      responses:
        '200':
          description: Lista de superhéroes paginada
          content:
            application/json:
              schema:
                type: object
                properties:
                  page:
                    type: integer
                    example: 1
                  per_page:
                    type: integer
                    example: 10
                  total:
                    type: integer
                    example: 12
                  total_pages:
                    type: integer
                    example: 2
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 4
                        Nombre:
                          type: string
                          example: "Voltrax"
                        Peso:
                          type: number
                          example: 80
                        Altura:
                          type: number
                          example: 1.9
                        Poder:
                          type: number
                          example: 83
                        created:
                          type: string
                          format: date-time
                          example: "2025-06-23T23:00:28+00:00"

    delete:
      summary: Eliminar un superhéroe por ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                  example: 1
                  
                  
      responses:
        '200':
          description: Superhéroe eliminado exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Superhéroe eliminado correctamente
        '400':
          description: ID inválido o no proporcionado
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Solicitud inválida: ID no válido o no proporcionado"

  /superheroe.php/media:
    post:
      summary: Obtener tweets recientes relacionados con una consulta
      description: Llama a la API de Twitter para obtener los tweets más recientes relacionados con un término de búsqueda.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
                  example: "AAAAAAAAAAAAAAAAAAAAAC%2Fo2AEAAAAAvJyXjeidF541YfJOIUZK8bLG2oU%3Dqo0DxtpPTx7FUYd3G172SEDOZ4EoSGV6bxcd1XLo7Am95Xq4P8"
                query:
                  type: string
                  example: "from:Marvel"
      responses:
        '200':
          description: Lista de tweets obtenidos exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  query:
                    type: string
                    example: "from:Marvel"
                  tweets:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          example: "1234567890"
                        text:
                          type: string
                          example: "Esto es un tweet de prueba."
                        author:
                          type: object
                          properties:
                            username:
                              type: string
                              example: "usuario123"
                            name:
                              type: string
                              example: "Nombre del usuario"
        '400':
          description: Token no proporcionado
        '500':
          description: Error al conectarse con la API de Twitter
